### ISSUE TITLE
Expose localforage.config?  (patch)

### ISSUE THREAD

**Issue by leegee** [mozilla/localForage-backbone#16]
It would be handy, at least for dev, to expose the `localforage.config` method — if you like the patch (I'm not sure I do), I can make a pull request if required.

    --- bower_components/localforage-backbone/dist/localforage.backbone.js	2015-02-24 13:26:05.000000000 +0100
    +++ bower_components/localforage-backbone/dist/localforage.backbone.patched.js	2015-02-24 13:26:17.000000000 +0100
    @@ -53,6 +53,9 @@
         // For now, we aren't complicated: just set a property off Backbone to
         // serve as our export point.
         Backbone.localforage = {
    +        getLocalforage: function () {
    +            return localforage
    +        },
             sync: function(name) {
                 var _this = this;
                 var sync = function(method, model, options) {

**Comment by tofumatt** [comment]
You're looking to expose the actual localForage object so you can get at config? That makes sense to me... I think `localforageInstance` would be a better property name, but I think it's fine to expose it. I'd accept that as a patch :smile: 

PS: Sorry for my late reply; moving countries right now and a bit backed up!

**Comment by leegee** [comment]
Thanks — good luck with your new country.
