### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by stephanebachelier** [mozilla/localForage-backbone#19]
An issue might not be the best way, but it's just to let you know that I'm currently working on the example.

The idea is to have a full example to play with (create, update, delete).

**Comment by tofumatt** [comment]
No worries! An issue is actually a great way to keep everyone posted, I like it! :-)

**Comment by stephanebachelier** [comment]
@tofumatt work is near complete.

I have a specific need that may be linked to the #22 where `x.sync.localforageKey`, `x` being a model or a collection. On the screenshot below you'll see that I expose the sync key of the model. I've refactored a little bit the code to expose the function which create the key for any collection or model. 

The example below is a full functional backbone example. I'll create a mobile application using this example to distribute on stores to make (my) mobile testing easier, and also as a webpage.

Chromium with localStorage driver selected
<img src="https://cloud.githubusercontent.com/assets/172615/6405290/d7a55c4c-be21-11e4-81c1-bb431ca18aa9.png" width="320" >

Chromium with IndexedDb driver selected
<img src="https://cloud.githubusercontent.com/assets/172615/6405289/d7a309a6-be21-11e4-9ea9-b1cd2d2044ec.png" width="320" >

Safari with localStorage driver selected, and no support for IndexedDb
<img src="https://cloud.githubusercontent.com/assets/172615/6405288/d7a1593a-be21-11e4-9f5e-2502c29db216.png" width="320" >
