### ISSUE TITLE
Destroying models doesn't remove reference from collection.

### ISSUE THREAD

**Issue by pplewa** [mozilla/localForage-backbone#7]
Collection is updated only on .save() and destroying models leaves orphaned model ids in the collection.

Below is a cumbersome workaround that kind of works, but this should be fixed.
```
collection.remove(model);
model.collection = collection;
model.save();
model.destroy();
```

**Comment by stephanebachelier** [comment]
@pplewa I've investigate your issue and IMO it's not a bug.
Calling `collection.remove` will never involve sync as it's only about removing a model from the collection.

The best way is to use `model.destroy`.

CC @tofumatt
